'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Download, Eye, Globe2, ShieldCheck } from 'lucide-react';
import { createPublicReport } from '@aes/core';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { EmptyState } from '@/components/empty-state';
import { PageHeading } from '@/components/page-heading';
import { useStudio } from '@/components/studio-provider';
import { downloadJson } from '@/lib/downloads';
import { publishPublicReport } from '@/lib/neon';

export default function ReportsPage() { const { runs } = useStudio(); const reportRuns = runs.filter((run) => run.juryResult && run.state === 'completed'); return <div className="mx-auto max-w-6xl"><PageHeading eyebrow="Redaction gate" title="Reports" description="Private bundles retain encrypted evidence. Public aesreport/v1 files contain only sanitized briefs, claim verdicts, and source links, and require an explicit preview and publish action." />{reportRuns.length ? <div className="grid gap-4 lg:grid-cols-2">{reportRuns.map((run) => <ReportCard key={run.id} run={run} />)}</div> : <EmptyState icon={ShieldCheck} title="No publishable result" body="A completed Research Jury result is required. Failed, running, and memory-only runs cannot become public claim reports." action={<Button nativeButton={false} render={<Link href="/jury/new" />}>Start Research Jury</Button>} />}</div>; }
function ReportCard({ run }: { run: any }) { const [preview, setPreview] = useState(false); const [confirmed, setConfirmed] = useState(false); const [publishing, setPublishing] = useState(false); const [shareId, setShareId] = useState<string | null>(null); const report = createPublicReport(run); const publish = async () => { setPublishing(true); try { setShareId(await publishPublicReport(report)); } finally { setPublishing(false); } }; return <article className="paper rounded-[24px] p-5"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#cfe3dc]"><Globe2 size={20} /></span><span className="rounded-full bg-[#f0ebe2] px-3 py-1 text-[10px] font-black uppercase tracking-wider">aesreport/v1</span></div><h2 className="mt-5 text-lg font-extrabold">{run.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[var(--muted-ink)]">{report.summary}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPreview((value) => !value)}><Eye />{preview ? 'Hide preview' : 'Redaction preview'}</Button><Button variant="outline" onClick={() => downloadJson(`${report.reportId}.aesreport.json`, report)}><Download />Download</Button></div>{preview && <pre className="scrollbar-thin mt-4 max-h-72 overflow-auto rounded-2xl bg-[var(--ink)] p-4 text-[11px] leading-5 text-[var(--cream)]">{JSON.stringify(report, null, 2)}</pre>}<label className="mt-4 flex cursor-pointer items-start gap-3 rounded-2xl bg-[#fff8df] p-4 text-xs leading-5"><Checkbox checked={confirmed} onCheckedChange={(checked) => setConfirmed(checked === true)} /><span>I reviewed the redacted payload. Publishing creates a public, revocable share record; it does not expose the private .aesrun bundle.</span></label><Button className="mt-3 w-full" disabled={!preview || !confirmed || publishing || Boolean(shareId)} onClick={publish}>{publishing ? 'Publishing sanitized report…' : shareId ? 'Published' : 'Publish public report'}</Button>{shareId && <Link href={`/share/${shareId}`} className="mt-3 block text-center text-sm font-bold underline">Open public share</Link>}</article>; }
