'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, Check, ChevronLeft, ChevronRight, CircleDashed, Download, GitBranch, RadioTower } from 'lucide-react';
import Link from 'next/link';
import type { EncryptedRunBundle, RunRecord } from '@aes/contracts';
import { analyzeEventGraph } from '@aes/core';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { PageHeading } from './page-heading';
import { StateBadge } from './state-badge';
import { useStudio } from './studio-provider';
import { downloadJson } from '@/lib/downloads';
import {
  isNeonSignInRequiredError,
  redirectToGoogleSignIn,
  uploadImmutableBundle,
} from '@/lib/neon';

export function RunDetail({ id }: { id: string }) {
  const { runs, client, runnerOnline } = useStudio(); const [run, setRun] = useState<RunRecord | null>(runs.find((item) => item.id === id) ?? null); const [selected, setSelected] = useState(0); const [passphrase, setPassphrase] = useState(''); const [workspaceId, setWorkspaceId] = useState(''); const [recoveryConfirmed, setRecoveryConfirmed] = useState(false); const [bundle, setBundle] = useState<EncryptedRunBundle | null>(null); const [syncState, setSyncState] = useState<'idle' | 'syncing' | 'synced'>('idle'); const [open, setOpen] = useState(false);
  useEffect(() => { if (!run && runnerOnline) void client.getRun(id).then((result) => setRun(result.run)).catch(() => undefined); }, [client, id, run, runnerOnline]);
  useEffect(() => { const saved = localStorage.getItem('aes.workspace-id'); const value = saved && /^[0-9a-f-]{36}$/i.test(saved) ? saved : crypto.randomUUID(); localStorage.setItem('aes.workspace-id', value); setWorkspaceId(value); }, []);
  const graph = useMemo(() => run ? analyzeEventGraph(run.events) : null, [run]);
  if (!run || !graph) return <div className="paper rounded-[24px] p-8"><Link href="/recorder" className="font-bold underline">Return to recorder</Link><p className="mt-4 text-[var(--muted-ink)]">Run is not present in the current unlocked workspace.</p></div>;
  const event = graph.replay[selected];
  const exportBundle = async () => { const result = await client.createBundle(run.id, workspaceId, passphrase); downloadJson(`${run.id}.recovery.json`, result.recoveryKit); setRecoveryConfirmed(true); setBundle(result.bundle); downloadJson(`${run.id}.aesrun`, result.bundle); };
  const syncBundle = async () => { if (!bundle) return; setSyncState('syncing'); try { await uploadImmutableBundle(bundle, run); setSyncState('synced'); } catch (error) { setSyncState('idle'); if (isNeonSignInRequiredError(error)) redirectToGoogleSignIn(); else throw error; } };
  return <div className="mx-auto max-w-7xl"><Link href="/recorder" className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm font-bold"><ArrowLeft size={17} />All runs</Link><PageHeading eyebrow={`${run.module} · ${run.id}`} title={run.title} description={`${run.events.length} immutable evidence events · created ${new Date(run.createdAt).toLocaleString()}`} actions={<div className="flex items-center gap-2"><StateBadge state={run.state} /><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button variant="outline" className="min-h-11 rounded-xl bg-white"><Download />Export</Button>} /><DialogContent className="rounded-[24px] bg-[var(--paper)]"><DialogHeader><DialogTitle>Export private .aesrun</DialogTitle><DialogDescription>A new workspace key encrypts this version. Downloading the recovery kit is part of the export gate.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label htmlFor="workspace-id">Workspace ID</Label><Input id="workspace-id" className="mt-2" value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} /></div><div><Label htmlFor="export-passphrase">Passphrase (12+ characters)</Label><Input id="export-passphrase" className="mt-2" type="password" value={passphrase} onChange={(event) => setPassphrase(event.target.value)} /></div><Button className="w-full" disabled={passphrase.length < 12} onClick={exportBundle}>{recoveryConfirmed ? 'Export another immutable version' : 'Download recovery kit and bundle'}</Button>{recoveryConfirmed && <p className="flex items-center gap-2 text-xs font-bold text-[#28755f]"><Check size={15} />Recovery kit downloaded. Store it offline.</p>}</div></DialogContent></Dialog></div>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.8fr)]"><section className="paper soft-grid rounded-[24px] p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow text-[var(--muted-ink)]">Causal replay</p><h2 className="mt-1 font-extrabold">Step {selected + 1} of {graph.replay.length}</h2></div><div className="flex gap-1"><Button size="icon" variant="outline" aria-label="Previous event" disabled={selected === 0} onClick={() => setSelected((value) => value - 1)}><ChevronLeft /></Button><Button size="icon" variant="outline" aria-label="Next event" disabled={selected >= graph.replay.length - 1} onClick={() => setSelected((value) => value + 1)}><ChevronRight /></Button></div></div><div className="overflow-x-auto pb-3"><div className="flex min-w-max items-center gap-2">{graph.replay.map((item, index) => <button key={item.eventId} onClick={() => setSelected(index)} className={`group flex min-h-24 w-36 flex-col items-start justify-between rounded-2xl border p-3 text-left transition ${selected === index ? 'border-[var(--pink)] bg-[#ffe1eb] shadow-md' : 'bg-[var(--paper)] hover:bg-white'}`}><span className="flex w-full items-center justify-between"><RadioTower size={16} /><span className={`h-2 w-2 rounded-full ${item.deliveryState === 'acknowledged' ? 'bg-green-600' : item.deliveryState === 'unknown' ? 'bg-amber-500' : 'bg-stone-400'}`} /></span><span><span className="block text-xs font-extrabold">{item.kind}</span><span className="mt-1 block text-[10px] text-[var(--muted-ink)]">{item.actor}</span></span></button>)}</div></div><div className="mt-4 rounded-2xl border bg-[var(--ink)] p-5 text-[var(--cream)]"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="eyebrow text-white/55">Selected evidence</p><h3 className="mt-1 text-lg font-bold">{event?.kind ?? 'No event'}</h3></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{event?.deliveryState}</span></div><dl className="mt-5 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-white/50">Actor</dt><dd className="mt-1 font-mono">{event?.actor}</dd></div><div><dt className="text-white/50">Digest</dt><dd className="mt-1 truncate font-mono">{event?.digest}</dd></div><div><dt className="text-white/50">Parents</dt><dd className="mt-1 font-mono">{event?.parentIds.join(', ') || 'root'}</dd></div><div><dt className="text-white/50">Time</dt><dd className="mt-1">{event && new Date(event.timestamp).toLocaleString()}</dd></div></dl><pre className="scrollbar-thin mt-5 max-h-80 overflow-auto rounded-xl bg-black/20 p-4 text-xs leading-5">{JSON.stringify(event?.payload, null, 2)}</pre></div></section>
      <aside className="space-y-5"><section className="paper rounded-[24px] p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">Integrity</h2><span className={`grid h-9 w-9 place-items-center rounded-full ${graph.complete ? 'bg-[#cce7dd]' : 'bg-[#ffd7d1]'}`}>{graph.complete ? <Check size={18} /> : <AlertTriangle size={18} />}</span></div><p className="mt-2 text-sm leading-6 text-[var(--muted-ink)]">{graph.complete ? 'The stored causal chain can be replayed completely.' : 'The chain is incomplete. Review the issues before relying on this run.'}</p>{bundle && recoveryConfirmed && <Button className="mt-4 w-full" variant="outline" disabled={syncState !== 'idle'} onClick={syncBundle}>{syncState === 'syncing' ? 'Uploading encrypted version…' : syncState === 'synced' ? 'Encrypted version synced' : 'Sync encrypted version'}</Button>}</section><section className="paper rounded-[24px] p-5"><h2 className="flex items-center gap-2 font-extrabold"><GitBranch size={18} />Detected issues</h2>{graph.issues.length ? <ul className="mt-4 space-y-3">{graph.issues.map((issue, index) => <li key={`${issue.kind}-${index}`} className="rounded-xl bg-[#fff0ed] p-3"><span className="text-xs font-black uppercase tracking-wider">{issue.kind}</span><p className="mt-1 text-xs leading-5 text-[var(--muted-ink)]">{issue.message}</p></li>)}</ul> : <div className="mt-4 flex items-center gap-3 rounded-xl bg-[#edf7f3] p-3 text-sm font-bold"><CircleDashed size={17} />No graph anomalies</div>}</section></aside>
    </div>
  </div>;
}
