'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { AlertCircle, ArrowLeft, CheckCircle2, ExternalLink, HelpCircle } from 'lucide-react';
import { PageHeading } from '@/components/page-heading';
import { StateBadge } from '@/components/state-badge';
import { useStudio } from '@/components/studio-provider';

export default function JuryResultPage() {
  const { id } = useParams<{ id: string }>(); const { runs } = useStudio(); const run = runs.find((item) => item.id === id);
  if (!run) return <div className="paper rounded-[24px] p-8"><Link href="/jury/new" className="font-bold underline">Start or import a Jury run</Link><p className="mt-3 text-[var(--muted-ink)]">This result is not in the current unlocked workspace.</p></div>;
  if (!run.juryResult) return <div><PageHeading eyebrow="Research Jury" title={run.title} description="The run did not produce an adjudicated result. Inspect its Recorder timeline for the failure evidence." actions={<StateBadge state={run.state} />} /><Link href={`/recorder/${run.id}`} className="font-bold underline">Open Flight Recorder</Link></div>;
  const result = run.juryResult; const sources = new Map(result.sources.map((source) => [source.id, source]));
  return <div className="mx-auto max-w-7xl"><Link href="/jury/new" className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm font-bold"><ArrowLeft size={17} />New question</Link><PageHeading eyebrow={`Adjudicated · ${result.sources.length} sources`} title={run.title} description={result.briefEn} actions={<div className="flex gap-2"><StateBadge state={run.state} /><Link href={`/recorder/${run.id}`} className="inline-flex min-h-10 items-center rounded-xl border bg-white px-3 text-sm font-bold">Evidence timeline</Link></div>} />
    <section className="paper overflow-hidden rounded-[24px]"><div className="border-b p-5"><p className="eyebrow text-[var(--muted-ink)]">Claim table</p><h2 className="mt-2 text-xl font-extrabold">Evidence-bound verdicts</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f4eee4] text-xs uppercase tracking-wider text-[var(--muted-ink)]"><tr><th className="p-4">Claim</th><th className="p-4">Verdict</th><th className="p-4">Rationale</th><th className="p-4">Sources</th></tr></thead><tbody>{result.claims.map((claim) => { const verdict = result.verdicts.find((item) => item.claimId === claim.id); return <tr key={claim.id} className="border-t align-top"><td className="max-w-sm p-4 font-semibold leading-6">{claim.text}</td><td className="p-4"><Verdict value={verdict?.status ?? 'unresolved'} /></td><td className="max-w-sm p-4 text-[var(--muted-ink)]">{verdict?.rationale ?? 'No adjudication rationale.'}</td><td className="p-4"><div className="space-y-2">{claim.sourceIds.map((sourceId) => { const source = sources.get(sourceId); return source ? <a key={sourceId} href={source.url} target="_blank" rel="noreferrer noopener" className="flex max-w-xs items-start gap-2 font-bold text-[var(--teal)] underline underline-offset-3">{source.title}<ExternalLink className="mt-0.5 shrink-0" size={13} /></a> : null; })}</div></td></tr>; })}</tbody></table></div></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="paper rounded-[24px] p-5"><h2 className="text-lg font-extrabold">Counterevidence</h2>{result.counterevidence.length ? <ul className="mt-4 space-y-3">{result.counterevidence.map((claim) => <li key={claim.id} className="rounded-2xl bg-[#fff0ed] p-4 text-sm leading-6">{claim.text}</li>)}</ul> : <p className="mt-3 text-sm text-[var(--muted-ink)]">No source-bound counterevidence was returned.</p>}</section><section className="paper rounded-[24px] p-5"><h2 className="text-lg font-extrabold">Unresolved questions</h2>{result.unresolvedQuestions.length ? <ul className="mt-4 space-y-3">{result.unresolvedQuestions.map((question) => <li key={question} className="flex gap-3 rounded-2xl bg-[#fff8df] p-4 text-sm leading-6"><HelpCircle className="mt-1 shrink-0" size={17} />{question}</li>)}</ul> : <p className="mt-3 text-sm text-[var(--muted-ink)]">The adjudicator did not identify an unresolved question.</p>}</section></div>
  </div>;
}
function Verdict({ value }: { value: 'supported' | 'disputed' | 'unresolved' }) { const Icon = value === 'supported' ? CheckCircle2 : value === 'disputed' ? AlertCircle : HelpCircle; const style = value === 'supported' ? 'bg-[#d9eee6] text-[#205b49]' : value === 'disputed' ? 'bg-[#ffe0da] text-[#87362d]' : 'bg-[#fff0bd] text-[#715b16]'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ${style}`}><Icon size={14} />{value}</span>; }
