'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowRight, FlaskConical, SearchCheck, Settings2, ShieldQuestion } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { ClayScene } from '@/components/clay-scene';
import { EmptyState } from '@/components/empty-state';
import { PageHeading } from '@/components/page-heading';
import { useStudio } from '@/components/studio-provider';

export default function NewJuryPage() {
  const { providers, runnerOnline, startJury } = useStudio(); const router = useRouter(); const [question, setQuestion] = useState(''); const [providerId, setProviderId] = useState(providers[0]?.id ?? ''); const [busy, setBusy] = useState(false);
  const submit = async () => { setBusy(true); try { const run = await startJury(question, providerId); router.push(`/jury/${run.id}`); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Module 03 · teal evidence" title="Research Jury" description="A bounded three-role workflow. Researcher gathers source-linked claims, Challenger hunts contradictions and staleness, and Adjudicator must abstain when evidence cannot support a verdict." />
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_420px]"><section className="paper rounded-[26px] p-5 sm:p-7">{!providers.length ? <EmptyState icon={Settings2} title="Hosted execution is not ready" body="The deployment administrator must connect Neon Auth, the server-side provider, and the hosted usage database. Members never configure executables or API keys." action={<Button nativeButton={false} render={<Link href="/settings" />}>View hosted status</Button>} /> : <><div><Label htmlFor="research-question" className="text-sm font-extrabold">What should the jury investigate?</Label><Textarea id="research-question" className="mt-3 min-h-44 rounded-2xl bg-[#fcf9f3] p-4 text-base leading-7" placeholder="Ask a precise, decision-relevant question. Include geography, timeframe, and the evidence standard when they matter." value={question} onChange={(event) => setQuestion(event.target.value)} /></div><div className="mt-5"><Label htmlFor="jury-provider" className="text-sm font-extrabold">Hosted provider</Label><Select value={providerId} onValueChange={(value) => setProviderId(value ?? '')}><SelectTrigger id="jury-provider" className="mt-3 min-h-12 rounded-xl bg-white"><SelectValue placeholder="Choose provider" /></SelectTrigger><SelectContent>{providers.map((provider) => <SelectItem key={provider.id} value={provider.id}>{provider.name} · {provider.model}</SelectItem>)}</SelectContent></Select></div><div className="mt-5 rounded-2xl border bg-[#e8f1ee] p-4 text-xs leading-5 text-[var(--teal)]"><strong>Execution boundary:</strong> maximum six invocations, one repair attempt per role, sequential roles, authenticated usage limits, and no message-supplied action URL execution.</div><Button className="mt-5 min-h-13 w-full rounded-2xl bg-[var(--teal)] text-white" disabled={!runnerOnline || question.trim().length < 10 || !providerId || busy} onClick={submit}>{busy ? 'Jury is examining evidence…' : <>Start hosted jury <ArrowRight /></>}</Button></>}</section><aside className="paper overflow-hidden rounded-[26px] p-4"><ClayScene module="jury" className="rounded-[20px]" /><div className="px-1 pb-1 pt-4"><p className="eyebrow">Evidence roles</p><h2 className="mt-1 text-xl font-black">Three independent passes</h2><p className="mt-1 text-xs leading-5 text-[var(--muted-ink)]">Each role has a separate evidence duty before the final verdict is recorded.</p><div className="mt-4 divide-y divide-[var(--line)] rounded-[18px] border border-[var(--line)] bg-[#fcf9f3]"><Role icon={SearchCheck} label="Researcher" body="Creates claims only when they bind to source records." /><Role icon={ShieldQuestion} label="Challenger" body="Seeks counterevidence, stale data, and missing proof." /><Role icon={FlaskConical} label="Adjudicator" body="Assigns supported, disputed, or unresolved—not consensus." /></div></div></aside></div>
  </div>;
}
function Role({ icon: Icon, label, body }: { icon: typeof FlaskConical; label: string; body: string }) { return <div className="flex items-start gap-3 p-3.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8f1ee] text-[var(--teal)]"><Icon size={19} /></span><span><span className="block text-sm font-extrabold">{label}</span><span className="mt-1 block text-xs leading-5 text-[var(--muted-ink)]">{body}</span></span></div>; }
